# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.TextField(null=True)),
                ('direccion', models.TextField(null=True)),
                ('latitudGeografica', models.IntegerField(null=True)),
                ('longitudGeografica', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeLicencia', models.IntegerField(null=True)),
                ('catergoriaLicencia', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.TextField(null=True)),
                ('numeroDocumento', models.TextField(null=True)),
                ('nombres', models.TextField(null=True)),
                ('apellidos', models.TextField(null=True)),
                ('cargo', models.TextField(null=True)),
                ('fechaNacimiento', models.DateTimeField(null=True)),
                ('sangreRH', models.TextField(null=True)),
                ('correo', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventaio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSolicitud', models.DateTimeField(auto_now_add=True, null=True)),
                ('direccionEntrega', models.CharField(blank=True, default='', max_length=100)),
                ('fechaEntregaMax', models.DateTimeField(null=True)),
                ('esPagoEnEfectivo', models.BooleanField()),
                ('latitudGeografica', models.IntegerField(null=True)),
                ('longitudGeografica', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(null=True)),
                ('descripcion', models.TextField(null=True)),
                ('precio', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAbastecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSolicitud', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionesRecorridas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.IntegerField(null=True)),
                ('longitud', models.IntegerField(null=True)),
                ('fechaSolicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.IntegerField(null=True)),
                ('longitud', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UltimaUbicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.IntegerField(null=True)),
                ('longitud', models.IntegerField(null=True)),
                ('fechaSolicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='envio',
            name='code',
        ),
        migrations.AlterField(
            model_name='envio',
            name='direccionEntrega',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='fechaEntregaMaxima',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='fechaSolicitud',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
